<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;

/**
 * Class Meta
 *
 * @property integer             $id
 * @property string              $name
 * @property string              $slug
 * @property string              $description
 * @property integer             $count
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 *
 * @package App
 */
abstract class Meta extends Model
{
    const TYPE = '';

    protected $table = 'metas';

    protected $fillable = [
        'name', 'slug', 'description', 'type',
    ];

    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($meta) {
            $meta->type = static::TYPE;
        });

        static::deleted(function ($meta) {
            // 删除该标签和所有文章的关联
           $meta->posts()->sync([]);
        });

        // 只查询出和当前 Model TYPE 相同的数据
        static::addGlobalScope('type', function (Builder $builder) {
            $builder->where('type', static::TYPE);
        });
    }

    public function posts()
    {
        return $this->belongsToMany(Post::class, 'content_meta', 'meta_id', 'content_id');
    }
}
