<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

abstract class Meta extends Model
{
    const TYPE = '';

    protected $table = 'metas';

    protected $fillable = [
        'name', 'slug', 'description', 'type',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($user) {
            $user->type = static::TYPE;
        });
    }
}
